// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mdxnshcwfrgdmkrvhamo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1keG5zaGN3ZnJnZG1rcnZoYW1vIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk0ODIwMTMsImV4cCI6MjA2NTA1ODAxM30.J2_lTqZSWIsNKTTW1hsMUnV6J1G-9KeDtfILBjH3uJw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);